version: "3.7"

services:
  logsv6:
    image: xnetinho/logsv6:latest
    environment:
      - TZ=America/Recife
      # Gere um token seguro em https://senhasegura.remontti.com.br
      - TOKEN=seu_token
      - LANG=pt-br
      - DB_HOST=mysql
      - DB_USER=logsv6
      - DB_PASSWORD=logsv6
      - DB_NAME=logsv6
    # ports:
    #  - 80:80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # labels:
        # - traefik.enable=true
        # - traefik.http.routers.perfexcrm.rule=Host(`logsv6.provedor.com.br`)
        # - traefik.http.services.perfexcrm.loadbalancer.server.port=80
        # - traefik.http.routers.perfexcrm.service=perfexcrm
        # - traefik.http.routers.perfexcrm.tls.certresolver=letsencryptresolver
        # - traefik.http.routers.perfexcrm.entrypoints=websecure
        # - traefik.http.routers.perfexcrm.tls=true
    networks:
      - network_public
      
networks:
  network_public:
    external: true
    name: network_public